checkpoint:
  simclr: /home/sdastani/projects/rrg-ebrahimi/sdastani/CRN/checkpoints/checkpoint_0100.pth.tar

parameter:
  sequence_length: 10
  batch_size: 15
  input_size: 128
  hidden_size: 256
  num_layers: 2
  num_classes: 101
  epochs: 15